import { Type } from "@sinclair/typebox";
import { stringEnum } from "openclaw/plugin-sdk/core";
import {
  DeviceIdField,
  TimeoutField,
  WireguardInterfaceSchema,
  WireguardPeerSchema,
} from "./common.js";

export const SetWireguardVpnSchema = Type.Object(
  {
    deviceId: DeviceIdField,
    interface: WireguardInterfaceSchema,
    peers: Type.Optional(Type.Array(WireguardPeerSchema)),
    timeoutMs: TimeoutField,
  },
  { additionalProperties: false },
);

export const ResetWireguardVpnSchema = Type.Object(
  {
    deviceId: DeviceIdField,
    interface: Type.Optional(
      Type.String({ minLength: 1, description: "WireGuard interface name to reset. Defaults to wg0." }),
    ),
    flushRoutes: Type.Optional(
      Type.Boolean({
        description: "Whether to flush static routes bound to the WireGuard interface. Defaults to true.",
      }),
    ),
    timeoutMs: TimeoutField,
  },
  { additionalProperties: false },
);

export const SetVpnRoutesSchema = Type.Object(
  {
    deviceId: DeviceIdField,
    mode: stringEnum(["selective"] as const, {
      description:
        "Routing mode: selective (individual CIDR routes managed through explicit static routes).",
    }),
    routePlanFile: Type.Optional(
      Type.String({
        minLength: 1,
        description:
          "Optional JSON file path generated by clawwrt_collect_wireguard_protected_routes. When provided in selective mode, the tool reads routes for the target device from this file.",
      }),
    ),
    routes: Type.Optional(
      Type.Array(
        Type.String({
          minLength: 1,
          description: "CIDR destination to route through VPN, e.g. 1.2.3.0/24.",
        }),
      ),
    ),
    timeoutMs: TimeoutField,
  },
  { additionalProperties: false },
);

export const CollectWireguardProtectedRoutesSchema = Type.Object(
  {
    deviceIds: Type.Array(Type.String({ minLength: 1 }), {
      minItems: 1,
      description:
        "Selected device IDs to include in the WireGuard protected-route file. The tool fetches each device's br-lan CIDR and includes the shared wg0 subnet for each device.",
    }),
    serverTunnelIp: Type.String({
      minLength: 1,
      description:
        "Server-side WireGuard tunnel CIDR, e.g. 10.0.0.1/24. The network portion is added to every device's protected routes.",
    }),
    timeoutMs: TimeoutField,
  },
  { additionalProperties: false },
);

export const VerifyWireguardConnectivitySchema = Type.Object(
  {
    deviceIds: Type.Optional(
      Type.Array(Type.String({ minLength: 1 }), {
        description:
          "Explicit list of device IDs to verify. When omitted, all online devices are checked.",
      }),
    ),
    pingTargets: Type.Optional(
      Type.Array(Type.String({ minLength: 1 }), {
        description:
          "Tunnel IPs to ping from the VPS side (e.g. [\"10.0.0.2\", \"10.0.0.3\"]). Skipped when omitted.",
      }),
    ),
    timeoutMs: TimeoutField,
  },
  { additionalProperties: false },
);
